apiVersion: v1
kind: Service
metadata:
  name: app-youtube-miner-service
spec:
  selector:
    app: youtube-miner-deployment
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer